name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - AGENTS.md
      - docs/**
      - .gitignore
      - .dockerignore

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build \
          -t ghcr.io/loadept/notifier:latest \
          -t ghcr.io/loadept/notifier:${{ github.sha }} \
          .

          docker push ghcr.io/loadept/notifier:latest
          docker push ghcr.io/loadept/notifier:${{ github.sha }}
